# Generated by Django 4.0.3 on 2022-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_intime_searching_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searching',
            name='vehicle_no',
            field=models.CharField(max_length=122),
        ),
    ]
